spring:
  security:
    filter:
      order: 2147483647
  data:
    redis:
      lettuce:
        pool:
          min-idle: 2
          enabled: true
common-lib:
  openapi:
    disabled: true
  rest-template:
    max-log-body-size: "146800640"
webflux:
  logging:
    gateway:
      max-body-size: "146800640"
      log-body: true


